Channel365.Web.Site/Controllers/ChannelController.cs
using Channel365.Data.Entities;
using Channel365.Models;
using Channel365.Web.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Channel365.Web.Controllers
{
    public class ChannelController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ApplicationDbContext context;

        public ChannelController(
            UserManager<ApplicationUser> userManager,
            ApplicationDbContext context)
        {
            this.userManager = userManager;
            this.context = context;
        }

        public async Task<IActionResult> Index(string id)
        {
            var user = await userManager.GetUserAsync(User);
            
            if (user != null && user.Id != id)
            {
                var subscription = await context.UserFollowings
                .AsNoTracking()
                .SingleOrDefaultAsync(x => x.ObserverId == user.Id && x.TargetId == id);

                if (subscription == null)
                    ViewData["Subscribed"] = false;
                else
                    ViewData["Subscribed"] = true;
            }

            var channel = await userManager.FindByIdAsync(id);
            if (channel == null)
                return NotFound();

            return View(channel);
        }
        public async Task<IActionResult> Videos(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
                return NotFound();

            user.VideoLibrary = await context.Videos
                                .Where(x => x.ApplicationUser.Id == id && x.IsPrivate == false).ToListAsync();

            return View(user);
        }
        public async Task<IActionResult> Playlists(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
                return NotFound();

            user.UserPlaylist = await context.Playlists
                                .Where(x => x.ApplicationUser.Id == id && x.PlaylistVisibility == PlaylistVisibility.Public)
                                .Include(x => x.VideosInPlaylists).ThenInclude(x => x.Video)
                                .ToListAsync();

            return View(user);
        }
        public async Task<IActionResult> Subscriptions(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
                return NotFound();

            // Load subscribers from user
            //var user.Following = await context.User.Include(x => x.Subscribers)ToListAsync();

            return View(user);
        }
    }
}

Channel365.Web.Site/Controllers/VideoController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Channel365.Data.Entities;
using Channel365.Data.Models.Video;
using Channel365.Models;
using Channel365.Web.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Channel365.Web.Controllers
{

    public class VideoController : Controller
    {
        private readonly ApplicationDbContext context;
        private UserManager<ApplicationUser> user;

        public VideoController(ApplicationDbContext context, UserManager<ApplicationUser> user)
        {
            this.context = context;
            this.user = user;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Video(Guid id)
        {
            var currentUser = await user.GetUserAsync(User);

            if (currentUser != null)
                ViewBag.User = currentUser;

            var video = await context.Videos
                .Include(x => x.ApplicationUser).ThenInclude(x => x.VideoLibrary)
                .Include(x => x.CommentVideos).ThenInclude(x => x.ApplicationUser)
                .Include(x => x.LikesAndDislikes)
                .FirstOrDefaultAsync(x => x.VideoId == id);

            if (video == null)
                return NotFound();

            return View(video);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateComment(Guid videoId, string message)
        {
            //! Check if a user is logged in, if not, respond with 403 - Forbidden.
            var commenter = await user.GetUserAsync(User);
            if (commenter == null)
                return Json("403");

            var comments = new CommentVideoModel
            {
                VideoId = videoId,
                CommentBody = message,
                ApplicationUser = commenter,
                Name = User.Identity.Name,
                PostedAt = DateTime.Now
            };

            context.CommentVideos.Add(comments);
            await context.SaveChangesAsync();

            var response = await context.CommentVideos
                .AsNoTracking()
                .Include(x => x.ApplicationUser)
                .SingleOrDefaultAsync(x => x.CommentId == comments.CommentId);

            return Json(response);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteComment(Guid videoId, Guid commentId)
        {
            var currentUser = await user.GetUserAsync(User);
            if (currentUser == null)
                return Json("404");

            var commentToDelete = await context.CommentVideos
                .SingleOrDefaultAsync(x => x.CommentId == commentId && x.VideoId == videoId && x.ApplicationUser.Id == currentUser.Id);

            if (commentToDelete == null)
                return Json("404");

            context.CommentVideos.Remove(commentToDelete);
            await context.SaveChangesAsync();

            return Json("204");
        }
        [HttpGet]
        public async Task<IActionResult> UpdateCommentCount(Guid videoId)
        {
            var obj = await context.CommentVideos
                .AsNoTracking()
                .Where(x => x.VideoId == videoId)
                .ToListAsync();

            var count = obj.Count();

            return Json(count);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteVideo(Guid id)
        {
            // Get the logged in user
            var currentUser = await user.GetUserAsync(User);

            // If current user is null, something went wrong
            if (currentUser == null)
                return NotFound();

            // Get video from db and check if it's Id matches argument Id 
            // and that the videos related user-Id matches currentUser Id
            var video = await context.Videos
                        .FirstOrDefaultAsync(x => x.VideoId == id && x.ApplicationUser.Id == currentUser.Id);

            if (video == null)
                return NotFound();

            context.Videos.Remove(video);
            await context.SaveChangesAsync();

            return Redirect("/Identity/Account/Manage/Uploads/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LikeVideo(Guid videoId, bool like)
        {
            var usersId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (usersId == null)
                return Json("403");

            var videoLikeStatus = await context.LikesAndDislikes
                .SingleOrDefaultAsync(x => x.VideoId == videoId && x.UserId == usersId);

            //! If no Like/Dislike exists, create new
            if (videoLikeStatus == null)
            {
                var newLikeStatus = new LikeDislikeModel
                {
                    UserId = usersId,
                    VideoId = videoId,
                    Like = like
                };
                context.LikesAndDislikes.Add(newLikeStatus);
                await context.SaveChangesAsync();

            } //! If new value != current, update current to new
            else if (videoLikeStatus.Like != like)
            {
                videoLikeStatus.Like = like;

                context.Entry(videoLikeStatus).State = EntityState.Modified;
                try
                {
                    await context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (context.LikesAndDislikes.Any(x => x.VideoId == videoId && x.UserId == usersId))
                        return NotFound();
                    else
                        throw;
                }
            }
            else
            {
                //! If new value == current, delete the like
                context.LikesAndDislikes.Remove(videoLikeStatus);
                await context.SaveChangesAsync();
            }

            //! Load video and store new nr of likes/dislikes
            var video = await context.Videos
                .AsNoTracking()
                .Include(x => x.LikesAndDislikes)
                .SingleOrDefaultAsync(x => x.VideoId == videoId);

            int likeCount = video.LikesAndDislikes
                .Where(x => x.Like == true)
                .Count();

            int dislikeCount = video.LikesAndDislikes
                .Where(x => x.Like == false)
                .Count();

            //! Format counts for easy split
            string result = likeCount + ":" + dislikeCount;

            return Json(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveLike(Guid videoId)
        {
            var usersId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var likeToRemove = await context.LikesAndDislikes.FirstOrDefaultAsync(x => x.VideoId == videoId && x.UserId == usersId);
            if (likeToRemove != null)
            {
                context.LikesAndDislikes.Remove(likeToRemove);
                await context.SaveChangesAsync();

                return Json("204");
            }

            return Json("404");
        }

        [HttpGet]
        public async Task<IActionResult> LikedVideos()
        {
            var currUser = await user.GetUserAsync(User);

            if (currUser == null)
                return LocalRedirect("/Identity/Account/Login");

            currUser = await context.Users
                .AsNoTracking()
                .Include(x => x.LikesAndDislikes).ThenInclude(x => x.Video).ThenInclude(x => x.ApplicationUser)
                .FirstOrDefaultAsync(x => x.Id == currUser.Id);

            return View(currUser);
        }

        public IActionResult FollowUser(string userName)
        {
            var target = context.Users.FirstOrDefault(x => x.UserName == userName);
            var observer = User.FindFirstValue(ClaimTypes.NameIdentifier);



            return View();
        }

        public IActionResult Edit(Guid id)
        {
            var video = context.Videos.FirstOrDefault(x => x.VideoId == id);
            if (video == null)
            {
                return NotFound();
            }
            return View(video);
        }
        public IActionResult EditVideo(Guid VideoId, string VideoTitle, string VideoDescription, bool IsPrivate)
        {
            var editVideo = context.Videos.FirstOrDefault(x => x.VideoId == VideoId);

            editVideo.VideoTitle = VideoTitle ?? editVideo.VideoTitle;
            editVideo.VideoDescription = VideoDescription ?? editVideo.VideoDescription;
            editVideo.IsPrivate = IsPrivate;

            context.Entry(editVideo).State = EntityState.Modified;

            try
            {
                context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (context.Videos.Any(x => x.VideoId == VideoId))
                    return NotFound();
                else
                    throw;
            }
            return LocalRedirect("/Identity/Account/Manage/Uploads");
        }
    }
}

Channel365.Web.Site/Views/Shared/Components/Video/Default.cshtml
@model IEnumerable<Channel365.Models.VideoModel>

<div class="d-flex flex-row flex-wrap align-items-center mt-2 justify-content-center mb-4 flex-grow-1">
    @foreach (var item in Model) {
    <div class="video-display-container">
        <a asp-controller="Video" asp-action="Video" asp-route-id="@item.VideoId" class="room-button">
            <img src=@item.VideoImage class="videoImages" width="300" style="min-height:200px" />
        </a>
        <div class="row">
            <div class="col-auto pr-0">
                <img src="@item.ApplicationUser.UserImageUrl" class="rounded-circle mt-3" width="25" height="25" />
            </div>
            <div class="col">
                <div class="video-display-title d-inline-block mt-1">
                    @if (item.VideoTitle.Length > 25)
                    {
                        var shortenedTitle = item.VideoTitle.Substring(0, 25) + "...";
                        <p class="vid-title-text mb-0 pt-1">@shortenedTitle</p>
                    }
                    else
                    {
                        <p class="vid-title-text mb-0 pt-1">@item.VideoTitle</p>
                    }
                </div>
            </div>
            <div class="col-12">
                <div class="vid-details">
                    <small>
                        <a class="text-info" asp-controller="Channel" asp-action="Index" asp-route-id="@item.ApplicationUser.Id">@item.ApplicationUser.UserName</a>
                        <span class="text-muted">&bull;</span>
                        <svg style="vertical-align:initial" class="bi bi-hand-thumbs-up" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16v-1c.563 0 .901-.272 1.066-.56a.865.865 0 0 0 .121-.416c0-.12-.035-.165-.04-.17l-.354-.354.353-.354c.202-.201.407-.511.505-.804.104-.312.043-.441-.005-.488l-.353-.354.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315L12.793 9l.353-.354c.353-.352.373-.713.267-1.02-.122-.35-.396-.593-.571-.652-.653-.217-1.447-.224-2.11-.164a8.907 8.907 0 0 0-1.094.171l-.014.003-.003.001a.5.5 0 0 1-.595-.643 8.34 8.34 0 0 0 .145-4.726c-.03-.111-.128-.215-.288-.255l-.262-.065c-.306-.077-.642.156-.667.518-.075 1.082-.239 2.15-.482 2.85-.174.502-.603 1.268-1.238 1.977-.637.712-1.519 1.41-2.614 1.708-.394.108-.62.396-.62.65v4.002c0 .26.22.515.553.55 1.293.137 1.936.53 2.491.868l.04.025c.27.164.495.296.776.393.277.095.63.163 1.14.163h3.5v1H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z" />
                        </svg>
                        @item.LikesAndDislikes.Where(x => x.Like == true).Count()
                        <span class="text-muted">&bull;</span>
                        <svg class="bi bi-hand-thumbs-down" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28v1c.563 0 .901.272 1.066.56.086.15.121.3.121.416 0 .12-.035.165-.04.17l-.354.353.353.354c.202.202.407.512.505.805.104.312.043.44-.005.488l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.415-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.353.352.373.714.267 1.021-.122.35-.396.593-.571.651-.653.218-1.447.224-2.11.164a8.907 8.907 0 0 1-1.094-.17l-.014-.004H9.62a.5.5 0 0 0-.595.643 8.34 8.34 0 0 1 .145 4.725c-.03.112-.128.215-.288.255l-.262.066c-.306.076-.642-.156-.667-.519-.075-1.081-.239-2.15-.482-2.85-.174-.502-.603-1.267-1.238-1.977C5.597 8.926 4.715 8.23 3.62 7.93 3.226 7.823 3 7.534 3 7.28V3.279c0-.26.22-.515.553-.55 1.293-.138 1.936-.53 2.491-.869l.04-.024c.27-.165.495-.296.776-.393.277-.096.63-.163 1.14-.163h3.5v-1H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z" />
                        </svg>
                        @item.LikesAndDislikes.Where(x => x.Like == false).Count()
                        <span class="text-muted">&bull;</span>
                        <svg class="bi bi-chat-square-dots" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h2.5a2 2 0 0 1 1.6.8L8 14.333 9.9 11.8a2 2 0 0 1 1.6-.8H14a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                            <path d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                        </svg>
                        @item.CommentVideos.Count()
                    </small>
                </div>
            </div>
        </div>

        @*<div class="video-display-title mt-3">
            @if (item.VideoTitle.Length > 34)
            {
                var shortenedTitle = item.VideoTitle.Substring(0, 34) + "...";
                <p class="vid-title-text mb-0">@shortenedTitle</p>
            }
            else
            {
                <p class="vid-title-text mb-0">@item.VideoTitle</p>
            }
        </div>
        <div class="video-display-desc">
            @if (item.VideoDescription.Length > 123)
            {
                var shortenedDesc = item.VideoDescription.Substring(0, 100) + "...";
                <p class="vid-desc-text">@shortenedDesc</p>
            }
            else
            {
                <p class="vid-desc-text">@item.VideoDescription</p>
            }
        </div>*@
    </div>
    }
</div>

<style>

    .video-display-container {
        max-width: 300px;
        max-height: 320px;
        height: 320px;
        margin: 10px;
    }
    .video-display-title {
        /* Style for vid title-container */
        font-weight: bold;
        overflow: hidden;
        max-width: 280px;
        color: #ffcd70;
    }
    .vid-title-text {
        /* Style for vid title */
    }
    .video-display-desc {
        max-width: 280px;
        max-height: 75px;
    }
    .vid-desc-text {
    }

    .room-button img {
        max-width: 300px;
        max-height: 200.66px;
    }

</style>